### ISSUE TITLE
Composite Key with binary key file

### ISSUE THREAD

**Issue by i4s-dvelez** [jorabin/KeePassJava2#11]
Hi,

I'm trying to use your library but it seems that only XML key files are supported, is there any workaround to use a Binary Key File?

Thanks!

**Comment by jorabin** [comment]
Not at present, I'm afraid.

**Comment by i4s-dvelez** [comment]
In case anyone need it.

I create a workaround:

public class MyCredentials implements Credentials {

    private final byte[] key;

    public MyCredentials(String password, InputStream inputStream) {
        MessageDigest md = Encryption.getMessageDigestInstance();
        byte[] pwKey = md.digest(password.getBytes());

        byte[] keyFileData = new byte[0];
        try {
            keyFileData = ByteStreams.toByteArray(inputStream);
        } catch (IOException e) {
            e.printStackTrace();
        }
        if(keyFileData == null) {
            throw new IllegalStateException("Could not read key file");
        } else {
            key = md.digest(Bytes.concat(pwKey, keyFileData));
        }
    }

    public byte[] getKey() {
        return this.key;
    }

}

**Comment by jorabin** [comment]
to be clear, this is for kdb files rather than kdbx?

**Comment by i4s-dvelez** [comment]
Yes, actually is for a kdb file generated with KeePass 1.x

**Comment by jorabin** [comment]
I had a problem using this, since it seems that I can only generate hex encoded kdb key files and this doesn't convert from hex. 

I've pushed a modification to KdbCredentials to the develop branch. It would be great if you could test it please. And if you have an example keyfile that is not hex encoded it would be useful to have this for testing.

**Comment by i4s-dvelez** [comment]
I'm afraid I also have hex encoded kdb file and I had to convert it before
open it:

File file = new File(keyFilePath);
String key = new String(IOUtils.toByteArray(new FileInputStream(file)));
PipedOutputStream out = new PipedOutputStream();
PipedInputStream in = new PipedInputStream(out);
Hex.decode(key, out);
out.close();

MyCredentials credentials = new MyCredentials(password, in);


2017-01-23 14:36 GMT+01:00 Jo <notifications@github.com>:

**Comment by i4s-dvelez** [comment]
I've tested your code with my kdb file and It works fine. But as I said my
key file is hex encoded...

2017-01-23 14:47 GMT+01:00 Diego Velez <diego.velez@innovation4security.com>
:

**Comment by jorabin** [comment]
OK, thanks. I'll merge to master anyway.
