### ISSUE TITLE
Support for kdbx_4 format

### ISSUE THREAD

**Issue by starksm64** [jorabin/KeePassJava2#13]
So I was trying the library on a KeePassX created database and found that the signature verification was failing. After looking at the version release notes:
http://keepass.info/news/n170109_2.35.html

I saw that there was a new KDBXv4 database format:
http://keepass.info/help/kb/kdbx_4.html

I'm looking into what changes are needed in kdb to support this format.

**Comment by jorabin** [comment]
Version 4 is not currently supported - wholesale changes implied to the file format, limited impact on the XML. I drew a diagram of the differences in Sept 2016 ... not sure this is still right as V4 was a proposal at the time.

**Comment by jorabin** [comment]
I just pushed a preliminary version to branch feat/v4 which is capable of reading V4 files - it is in development and contributions are welcome.

**Comment by ivanovpv** [comment]
Are there any news with respect to v.4?

**Comment by jorabin** [comment]
Hey Pavel - as mentioned above there is a version in branch feat/v4 which can read v4 files. Would be good if you could check that out and verify.

**Comment by robertvazan** [comment]
Ping. Is this project still maintained? I could also use KDBX 4 support. Other projects are starting to produce KDBX 4 files (in my case latest pykeepass) that are unreadable in Java. Anyone had success with the v4 branch?

**Comment by jorabin** [comment]
Hi @robertvazan the v4 branch contains code to read v4 files which as far as I know works, however I don't have any use for it myself at the moment, so it would be good if you could check compatibility with what you have.

I do plan to do some maintenance this holiday period, however the road to hell is paved with good intentions, as they say. Either way your feedback on v4 branch would be most welcome.

**Comment by robertvazan** [comment]
Actually, it would be better to do a unit test with sample KDBX 4 file rather than having someone do a one-off manual test. KDBX 4 file can be generated by latest pykeepass, but perhaps one of the GUI tools saves in the new format too.

I am short of time and I have meantime found a workaround that will allow me to continue using KDBX 3 files for some time, so I wouldn't help you with the manual test nor the unit test this time around, sorry.

**Comment by jorabin** [comment]
I just pushed the source for version 2.2-SNAPSHOT which offers read/write support for V4.

Better late than never?

**Comment by jorabin** [comment]
Closed in 2.2.1
