### ISSUE TITLE
compile error with Java 11

### ISSUE THREAD

**Issue by danielgrahl** [jorabin/KeePassJava2#30]
The project does not compile with Java 11 or later. JAXB has been removed from JavaSE and needs to be provided explicitly.

**Comment by jorabin** [comment]
I'm not convinced that JAXB has a future in this project. Other than stimulating the creation of an [XML schema](https://github.com/jorabin/KeePassJava2/blob/master/KDBX.3.1.xsd) the performance of the implementation isn't worth much? Does anyone use it?

**Comment by count-of-monte-keystone** [comment]
@jorabin I made a fork recently and I don't plan on keeping it. I think the most important features revolve around reading/writing to the database files. Do you plan on doing anything with keepasshttp or is that in a similar situation to JAXB?

**Comment by jorabin** [comment]
I've removed `keepasshttp` in 3.2-SNAPSHOT. JAXB still under review.

**Comment by jorabin** [comment]
closed in 2.2.1
