### ISSUE TITLE
Custom icons cause problems

### ISSUE THREAD

**Issue by schulbus13** [jorabin/KeePassJava2#33]
I was given a manually created kdbx file containing a few custom icons. If I load (and edit, but thats not yet relevant) and save the database with KeePassJava2, the following problems occur, depending on the kind of database implementation I use:

### SimpleDatabase
`SimpleDatabase.load(creds, input).save(creds, output);`

The following error is thrown
> org.simpleframework.xml.core.ElementException: Element 'CustomIconUUID' does not have a match in class org.linguafranca.pwdb.kdbx.simple.SimpleGroup at line 341

### JaxbDatabase
`JaxbDatabase.load(creds, input).save(creds, output);`

No error is thrown, but the custom icons are replaced with default blue folder icon (48). Also the entire file is skipped when I try to search something via the desktop application (Searching entries in this group: Disabled), which wasn't the case before.

### DomDatabaseWrapper
`DomDatabaseWrapper.load(creds, input).save(creds, output)`

Custom icons are still there and I can also still search via the desktop application, but the loading and saving takes a very long time (a couple of minutes for a ~200kB file).

Is there a way to preserve the custom icons and the searchability while using one of the faster database implementations?

**Comment by jorabin** [comment]
The Dom implementation intentionally leaves things as it finds them, but as you say at a cost of speed. For the other two tit looks like there is a mapping missing.

**Comment by jorabin** [comment]
Closed in 2.2.1
