### ISSUE TITLE
Support latest version of KeePass

### ISSUE THREAD

**Issue by codemonstur** [jorabin/KeePassJava2#39]
I created a keepass archive with the latest version of KeePassXC (2.1.7). When loading with KeePassJava2 2.1.4 I get this error:

     Exception in thread "main" java.lang.IllegalStateException: File version did not match

Code:

    public static void main(final String... args) throws Exception {
        final var credentials = new KdbxCreds("mypass".getBytes());
        try (final var inputStream = TestLoading.class.getResourceAsStream("myarchive.kdbx")) {
            final var database = SimpleDatabase.load(credentials, inputStream);
            System.out.println(database);
        }
    }

**Comment by jorabin** [comment]
Support for File version 4 added in KeePassJava2 3.2.

**Comment by jorabin** [comment]
Closed in 2.2.1
