### ISSUE TITLE
It Seems we haven't an API to set a property as "protected"

### ISSUE THREAD

**Issue by giusvale-dev** [jorabin/KeePassJava2#55]
(https://www.javadoc.io/doc/org.linguafranca.pwdb/database/latest/index.html)

**Comment by jorabin** [comment]
no. nor is there one to set "protect by default"

**Comment by giusvale-dev** [comment]
I think it should be a good idea to add this feature.

[https://keepass.info/help/base/security.html#:~:text=While%20KeePass%20is%20running%2C%20sensitive,not%20find%20any%20sensitive%20data](KeePass2 doc)

If you agree, please add this issue as a TODO task

**Comment by jorabin** [comment]
yes, we'll do this as part of v3

**Comment by jorabin** [comment]
noting that both of these features have been implemented as 2.2.3 see #60
